apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-application
  template:                         # This line was indented incorrectly.
    metadata:
      labels:
        app: java-application
    spec:
      containers:
      - name: devops-java:
        image: ranjeeth3302/devops-java:
        ports:
        - containerPort: 8080
