apiVersion: v1                         # Corrected apiVersion for a Service
kind: Service
metadata:
  name: java-app-service
  labels:
    app: java-app
spec:
  type: LoadBalancer
  selector:
    app: java-application
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP                      # Fixed typo: "protocal" to "protocol"
